apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: java-tester-scaledobject
  namespace: pga-backend
spec:
  scaleTargetRef:
    name: java-tester
  minReplicaCount: 0
  maxReplicaCount: 3
  cooldownPeriod: 600  # 10 minutos
  triggers:
    - type: rabbitmq
      metadata:
        queueName: java_tests
        queueLength: "1"
        host: "amqp://guest:guest@rabbitmq.pga-backend.svc.cluster.local:5672/"

