apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: python-tester-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: python-tester
  minReplicas: 0
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
