services:
  pga-backend:
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file: .env
    depends_on:
      - pga-db
    networks:
      - pga-network
  
  pga-db:
    image: postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./pga/src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql
      - postgres-data:/var/lib/postgresql/data
    networks:
      - pga-network

volumes:
  postgres-data:

networks:
  pga-network:
    driver: bridge