services:
  pga-backend:
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - CLIENT_ORIGIN_URL=${CLIENT_ORIGIN_URL}
      - OKTA_OAUTH2_ISSUER=${OKTA_OAUTH2_ISSUER}
      - OKTA_OAUTH2_AUDIENCE=${OKTA_OAUTH2_AUDIENCE}
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
      - PAYPAL_CLIENT_SECRET=${PAYPAL_CLIENT_SECRET}
    depends_on:
      - pga-db
    networks:
      - pga-network
  
  pga-db:
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_DB=pga
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
    - postgres-data:/var/lib/postgresql/data
    networks:
    - pga-network

volumes:
  postgres-data:
    external: true

networks:
  pga-network:
    driver: bridge