apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: marcossantangelo1@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx
          podTemplate:
            metadata:
              annotations:
                acme.cert-manager.io/http01-ingress-path-type: Prefix
                acme.cert-manager.io/http01-ingress-path: /
                acme.cert-manager.io/http01-ingress-class: nginx
