apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pga-db
  namespace: pga-db
spec:
  serviceName: pga-db-headless
  replicas: 1
  selector:
    matchLabels:
      app: pga-db
  template:
    metadata:
      labels:
        app: pga-db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: pga-secrets
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
