apiVersion: v1
kind: Service
metadata:
  name: pga-backend
  namespace: pga-backend
spec:
  type: LoadBalancer
  loadBalancerIP: 34.10.144.139
  selector:
    app: pga-backend
  ports:
    - port: 6060
      targetPort: 6060
      protocol: TCP
      name: http