apiVersion: v1
kind: Service
metadata:
  name: pga-backend
  namespace: pga-backend
spec:
  type: ClusterIP
  clusterIP: 10.2.0.100
  selector:
    app: pga-backend
  ports:
    - port: 6060
      targetPort: 6060
      protocol: TCP
      name: http