name: Backend Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: dagyss/pga-backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Image Tag
        id: vars
        run: echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build with Maven
        working-directory: pga/
        run: mvn clean package -DskipTests

      - name: Build and Push Docker Image
        working-directory: pga/
        run: |
          docker build \
            -f Dockerfile.github \
            --build-arg ENV_CONTENT="${{ secrets.DOTENV_FILE }}" \
            -t $IMAGE_NAME:${{ steps.vars.outputs.TAG }} .
          docker push $IMAGE_NAME:${{ steps.vars.outputs.TAG }}

      - name: Update Kubernetes Manifests
        run: |
          sed -i "s|image: .*|image: $IMAGE_NAME:${{ steps.vars.outputs.TAG }}|" deploy/backend-deployment.yaml
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add deploy/base/deployment.yaml
          git commit -m "Update image to $IMAGE_NAME:${{ steps.vars.outputs.TAG }}"
          git push
